### ISSUE TITLE
페이지 수정 요청

### ISSUE THREAD

**Issue by LeeA0** [upswp/SOLAFY_2.0.0#14]
### 1. 아래 오류 수정 부탁드립니다!
![image](https://user-images.githubusercontent.com/69910544/107147665-94f29680-6992-11eb-8414-12755d5e3b89.png)
- 다른 페이지 이동 후 successsignup페이지로 이동 시 다음과 같이 화면이 깨집니다.

![image](https://user-images.githubusercontent.com/69910544/107147713-e569f400-6992-11eb-8691-dceb2c6bb041.png)
- 다른 페이지 이동 후 findpassword페이지로 이동 시 다음과 같이 화면이 깨집니다.

### 2. 다음을 수정해주시면 감사하겠습니다.
https://github.com/upswp/SOLAFY_2.0.0/blob/d7318c20666176ea1d3dbfb264cee9d61f7b2076/front/src/pages/Index.vue#L3
- index.vue(로그인화면) 하단의 footer의 양 옆에 공백이 생기는 이유가 해당 줄의 q-pa-md class 때문인 것 같습니다.  해당 클래스 사용에 특별한 이유가 없으시다면 삭제해주시면 감사하겠습니다.

**Comment by upswp** [comment]
금일 확인 후 조치하겠습니다.

**Comment by upswp** [comment]
완료했습니다. MR 확인 부탁드려요! 😋
